name: fabricio

services:
  portifolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fabricio_portfolio
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.50"
    networks:
      - backbone_net

networks:
  backbone_net:
    external: true
